Abtract:Chúng ta  sẽ fine tune hyperparameter các model để train database 02

In [1]:
#load data 02
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df=pd.read_csv("../../data/processed/DB02.csv")

In [2]:
#chuẩn bị data để huân luyện 
from sklearn.model_selection import train_test_split
x=df.drop('Diabetes',axis=1)
y=df['Diabetes']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [3]:
x.head()

HighBP  HighChol   BMI  Smoker  PhysActivity  Fruits  Veggies  GenHlth  \
0     1.0       0.0  26.0     0.0           1.0     0.0      1.0      3.0   
1     1.0       1.0  26.0     1.0           0.0     1.0      0.0      3.0   
2     0.0       0.0  26.0     0.0           1.0     1.0      1.0      1.0   
3     1.0       1.0  28.0     1.0           1.0     1.0      1.0      3.0   
4     0.0       0.0  29.0     1.0           1.0     1.0      1.0      2.0   

   MentHlth  Sex   Age  Education  Income  
0       5.0  1.0   4.0        6.0     8.0  
1       0.0  1.0  12.0        6.0     8.0  
2       0.0  1.0  13.0        6.0     8.0  
3       0.0  1.0  11.0        6.0     8.0  
4       0.0  0.0   8.0        5.0     8.0

In [4]:
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes, dtype: float64

In [5]:
print(x.shape)
y.shape

(69057, 13)


(69057,)

In [6]:
cols_to_scale = ['BMI', 'GenHlth', 'MentHlth','Age','Education','Income']

In [7]:
#Scale dữ liệu
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[cols_to_scale]=sc.fit_transform(x_train[cols_to_scale])
x_train

HighBP  HighChol       BMI  Smoker  PhysActivity  Fruits  Veggies  \
11041     0.0       1.0 -0.832954     0.0           1.0     1.0      1.0   
27964     1.0       0.0 -0.552929     0.0           1.0     1.0      1.0   
30967     1.0       1.0 -0.412916     0.0           1.0     0.0      1.0   
895       0.0       1.0 -1.112979     1.0           1.0     1.0      1.0   
67503     1.0       0.0  1.127222     0.0           1.0     1.0      1.0   
...       ...       ...       ...     ...           ...     ...      ...   
37194     0.0       0.0  1.267235     0.0           0.0     0.0      1.0   
6265      1.0       1.0 -0.832954     1.0           1.0     1.0      1.0   
54886     1.0       1.0 -0.552929     1.0           1.0     1.0      0.0   
860       0.0       0.0 -0.132891     0.0           1.0     0.0      1.0   
15795     0.0       0.0 -0.832954     0.0           1.0     1.0      1.0   

        GenHlth  MentHlth  Sex       Age  Education    Income  
11041 -0.780723 -0.467193  0.0  0.487735   0.099975  0.620641  
27964 -0.780723  0.016710  0.0  1.535319   1.070990  0.620641  
30967  0.121808 -0.467193  0.0 -0.210655  -0.871040 -1.221673  
895   -1.683254 -0.467193  0.0  0.138540   0.099975  1.081219  
67503  0.121808 -0.467193  0.0  1.186124  -0.871040 -0.761094  
...         ...       ...  ...       ...        ...       ...  
37194  1.926870 -0.467193  1.0  0.487735   1.070990 -2.142830  
6265   1.024339  1.952324  1.0  0.487735  -2.813070 -1.682251  
54886  1.024339  3.162083  1.0  1.186124  -1.842055 -1.221673  
860    1.024339 -0.467193  0.0 -0.559849  -0.871040 -1.221673  
15795 -0.780723 -0.467193  0.0 -1.607433   1.070990  1.081219  

[55245 rows x 13 columns]

In [8]:
x_test[cols_to_scale]=sc.transform(x_test[cols_to_scale])
x_test

HighBP  HighChol       BMI  Smoker  PhysActivity  Fruits  Veggies  \
51238     1.0       1.0  0.007122     0.0           1.0     1.0      1.0   
15606     1.0       1.0 -0.412916     1.0           0.0     0.0      1.0   
39330     1.0       1.0 -0.132891     0.0           0.0     0.0      1.0   
44019     1.0       1.0 -0.272904     1.0           1.0     0.0      1.0   
45249     1.0       1.0  0.567172     0.0           0.0     1.0      1.0   
...       ...       ...       ...     ...           ...     ...      ...   
9350      1.0       1.0  1.267235     1.0           0.0     0.0      1.0   
31894     0.0       0.0 -1.393004     0.0           1.0     1.0      1.0   
47170     1.0       1.0 -0.272904     1.0           1.0     1.0      1.0   
51946     0.0       0.0 -0.412916     0.0           1.0     1.0      1.0   
10617     0.0       0.0  0.147134     0.0           1.0     1.0      1.0   

        GenHlth  MentHlth  Sex       Age  Education    Income  
51238 -1.683254 -0.467193  1.0  0.487735   1.070990  1.081219  
15606 -0.780723 -0.467193  1.0 -1.607433   1.070990  1.081219  
39330  0.121808 -0.467193  0.0  1.535319  -0.871040  0.160062  
44019  0.121808 -0.467193  1.0  0.138540  -0.871040  1.081219  
45249 -0.780723 -0.467193  1.0  0.836929   0.099975  0.620641  
...         ...       ...  ...       ...        ...       ...  
9350  -0.780723 -0.467193  0.0  0.138540  -0.871040 -0.761094  
31894 -1.683254 -0.225241  0.0  0.138540   1.070990  1.081219  
47170  1.926870 -0.467193  0.0  0.836929  -1.842055  0.620641  
51946  0.121808 -0.467193  0.0 -2.655017  -0.871040 -1.221673  
10617 -1.683254 -0.467193  1.0 -1.258238   1.070990  1.081219  

[13812 rows x 13 columns]

In [9]:
#đánh giá training bới cross-validation với k-fold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,f1_score,classification_report, confusion_matrix, accuracy_score
# Hàm đánh giá mô hình với các chỉ số chung
def evaluate_model(model, x_train, y_train, x_test, y_test):
    # Cross-validation với k=5 và tiêu chí đánh giá là 'accuracy'
    cv_scores = cross_val_score(model, x_train, y_train, cv=5, scoring='accuracy')
    print(f"{model.__class__.__name__} - Cross-validation scores:", cv_scores)
    print(f"Mean cross-validation score: {cv_scores.mean()}\n")
    
    # Dự đoán trên tập kiểm tra
    y_pred = model.predict(x_test)
    
    # Các chỉ số đánh giá trên tập kiểm tra
    print(f"{model.__class__.__name__} - Accuracy Score:", accuracy_score(y_test, y_pred))
    print(f"{model.__class__.__name__} - F1 Score:", f1_score(y_test, y_pred, average='weighted'))
    print(f"{model.__class__.__name__} - Classification Report:\n", classification_report(y_test, y_pred))
    print(f"{model.__class__.__name__} - Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("-" * 50)

In [ ]:
#thuật toán RandomForest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
param_grid = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2'],
    'bootstrap': [True, False] #lấy mẫu lại
}
rf=RandomForestClassifier()
rf_ramdom=RandomizedSearchCV(estimator=rf, param_distributions=param_grid, n_iter=100,random_state=42, n_jobs=-1)

In [11]:
rf_ramdom.fit(x_train,y_train)

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [None, 10, 20, 30],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [50, 100, 200, 300]},
                   random_state=42)

In [13]:
yRF_predict=rf_ramdom.predict(x_test)

In [14]:
#print best hyperparameter
rf_ramdom.best_params_

{'n_estimators': 200,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 10,
 'bootstrap': True}

In [31]:
evaluate_model(rf_ramdom, x_train, y_train, x_test, y_test)

RandomizedSearchCV - Cross-validation scores: [0.74875554 0.74432075 0.74558784 0.73563218 0.7328265 ]
Mean cross-validation score: 0.7414245633088967

RandomizedSearchCV - Accuracy Score: 0.7521720243266724
RandomizedSearchCV - F1 Score: 0.751469810605246
RandomizedSearchCV - Classification Report:
               precision    recall  f1-score   support

         0.0       0.77      0.70      0.73      6723
         1.0       0.74      0.80      0.77      7089

    accuracy                           0.75     13812
   macro avg       0.75      0.75      0.75     13812
weighted avg       0.75      0.75      0.75     13812

RandomizedSearchCV - Confusion Matrix:
 [[4725 1998]
 [1425 5664]]
--------------------------------------------------


In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Define parameter grid
param_grid = {
    'penalty': ['l1', 'l2'],#loại chuẩn hóa để tránh overfitting
    'C': [0.001, 0.01, 0.1, 1, 10, 100],#Điều khiển độ ngược chuẩn hóa
    'solver': ['liblinear'],#thuật toán tối ưu hóa hàm mất mát
    'class_weight': [None, 'balanced'],#giải quyết vấn đề dữ liệu mất cân bằng
    'max_iter': [1000, 1500, 2000]
}
lg=LogisticRegression()
lg_grid=GridSearchCV(estimator=lg, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)

In [16]:
lg_grid.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'class_weight': [None, 'balanced'],
                         'max_iter': [1000, 1500, 2000],
                         'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
             scoring='accuracy')

In [18]:
lg_grid.predict(x_test)

array([0., 0., 1., ..., 1., 0., 0.])

In [19]:
lg_grid.best_params_

{'C': 0.01,
 'class_weight': 'balanced',
 'max_iter': 1500,
 'penalty': 'l1',
 'solver': 'liblinear'}

In [32]:
evaluate_model(lg_grid, x_train, y_train, x_test, y_test)

GridSearchCV - Cross-validation scores: [0.7435062  0.74106254 0.73970495 0.73689927 0.7312879 ]
Mean cross-validation score: 0.738492171237216

GridSearchCV - Accuracy Score: 0.7470315667535476
GridSearchCV - F1 Score: 0.7468932355778204
GridSearchCV - Classification Report:
               precision    recall  f1-score   support

         0.0       0.75      0.73      0.74      6723
         1.0       0.75      0.77      0.76      7089

    accuracy                           0.75     13812
   macro avg       0.75      0.75      0.75     13812
weighted avg       0.75      0.75      0.75     13812

GridSearchCV - Confusion Matrix:
 [[4882 1841]
 [1653 5436]]
--------------------------------------------------


In [20]:
#Sử dụng Ensemble learing Stacking
from sklearn.ensemble import StackingClassifier
# Khởi tạo StackingClassifier
stacking_clf = StackingClassifier(
    estimators=[('rf', rf_ramdom), ('lg', lg_grid)],
    final_estimator=LogisticRegression(max_iter=1000,random_state=42)
)


In [21]:
stacking_clf.fit(x_train, y_train)

StackingClassifier(estimators=[('rf',
                                RandomizedSearchCV(cv=3,
                                                   estimator=RandomForestClassifier(),
                                                   n_iter=100, n_jobs=-1,
                                                   param_distributions={'bootstrap': [True,
                                                                                      False],
                                                                        'max_depth': [None,
                                                                                      10,
                                                                                      20,
                                                                                      30],
                                                                        'max_features': ['sqrt',
                                                                                         'log2'],
                                                                        'min_samples_leaf': [1,
                                                                                             2,
                                                                                             4],
                                                                        'min_samples_split': [2,
                                                                                              5,
                                                                                              10],
                                                                        'n_estimators': [50,
                                                                                         100,
                                                                                         200,
                                                                                         300]},
                                                   random_state=42)),
                               ('lg',
                                GridSearchCV(cv=5,
                                             estimator=LogisticRegression(),
                                             n_jobs=-1,
                                             param_grid={'C': [0.001, 0.01, 0.1,
                                                               1, 10, 100],
                                                         'class_weight': [None,
                                                                          'balanced'],
                                                         'max_iter': [1000,
                                                                      1500,
                                                                      2000],
                                                         'penalty': ['l1',
                                                                     'l2'],
                                                         'solver': ['liblinear']},
                                             scoring='accuracy'))],
                   final_estimator=LogisticRegression(max_iter=1000,
                                                      random_state=42))

In [23]:
yStack_pred=stacking_clf.predict(x_test)

In [33]:
# Đánh giá mô hình Stacking
evaluate_model(stacking_clf, x_train, y_train, x_test, y_test)

StackingClassifier - Cross-validation scores: [0.748122   0.74323468 0.74495429 0.73689927 0.73490814]
Mean cross-validation score: 0.741623676350801

StackingClassifier - Accuracy Score: 0.7518100202722271
StackingClassifier - F1 Score: 0.7515418620845992
StackingClassifier - Classification Report:
               precision    recall  f1-score   support

         0.0       0.76      0.72      0.74      6723
         1.0       0.75      0.78      0.76      7089

    accuracy                           0.75     13812
   macro avg       0.75      0.75      0.75     13812
weighted avg       0.75      0.75      0.75     13812

StackingClassifier - Confusion Matrix:
 [[4856 1867]
 [1561 5528]]
--------------------------------------------------


In [24]:
#fine tune final estimate of stacking 
from sklearn.ensemble import StackingClassifier
# Khởi tạo StackingClassifier
stacking_clf_finetune = StackingClassifier(
    estimators=[('rf', rf_ramdom), ('lg', lg_grid)],
    final_estimator=lg_grid
)


In [25]:
stacking_clf_finetune.fit(x_train, y_train)

StackingClassifier(estimators=[('rf',
                                RandomizedSearchCV(cv=3,
                                                   estimator=RandomForestClassifier(),
                                                   n_iter=100, n_jobs=-1,
                                                   param_distributions={'bootstrap': [True,
                                                                                      False],
                                                                        'max_depth': [None,
                                                                                      10,
                                                                                      20,
                                                                                      30],
                                                                        'max_features': ['sqrt',
                                                                                         'log2'],
                                                                        'min_samples_leaf': [1,
                                                                                             2,
                                                                                             4],
                                                                        'min_samples_split': [2,
                                                                                              5,
                                                                                              10],
                                                                        'n_estimators': [50,
                                                                                         100,
                                                                                         200,
                                                                                         300]},
                                                   random_state=42)),
                               ('lg',
                                GridSearchCV(cv...
                                                                          'balanced'],
                                                         'max_iter': [1000,
                                                                      1500,
                                                                      2000],
                                                         'penalty': ['l1',
                                                                     'l2'],
                                                         'solver': ['liblinear']},
                                             scoring='accuracy'))],
                   final_estimator=GridSearchCV(cv=5,
                                                estimator=LogisticRegression(),
                                                n_jobs=-1,
                                                param_grid={'C': [0.001, 0.01,
                                                                  0.1, 1, 10,
                                                                  100],
                                                            'class_weight': [None,
                                                                             'balanced'],
                                                            'max_iter': [1000,
                                                                         1500,
                                                                         2000],
                                                            'penalty': ['l1',
                                                                        'l2'],
                                                            'solver': ['liblinear']},
                                                scoring='accuracy'))

In [27]:
yStack_finetune_pred=stacking_clf.predict(x_test)

In [34]:
# Đánh giá mô hình Stacking với SVC
evaluate_model(stacking_clf_finetune, x_train, y_train, x_test, y_test)

StackingClassifier - Cross-validation scores: [0.74821251 0.74423025 0.74576885 0.73662775 0.73065436]
Mean cross-validation score: 0.741098741967599

StackingClassifier - Accuracy Score: 0.7515928178395598
StackingClassifier - F1 Score: 0.7512181808876417
StackingClassifier - Classification Report:
               precision    recall  f1-score   support

         0.0       0.76      0.72      0.74      6723
         1.0       0.74      0.79      0.76      7089

    accuracy                           0.75     13812
   macro avg       0.75      0.75      0.75     13812
weighted avg       0.75      0.75      0.75     13812

StackingClassifier - Confusion Matrix:
 [[4816 1907]
 [1524 5565]]
--------------------------------------------------


In [28]:
#fine tune final estimate of stacking is rf_random
from sklearn.ensemble import StackingClassifier
# Khởi tạo StackingClassifier
stacking_clf_finetuneRF = StackingClassifier(
    estimators=[('rf', rf_ramdom), ('lg', lg_grid)],
    final_estimator=rf_ramdom
)

In [29]:
stacking_clf_finetuneRF.fit(x_train, y_train)

StackingClassifier(estimators=[('rf',
                                RandomizedSearchCV(cv=3,
                                                   estimator=RandomForestClassifier(),
                                                   n_iter=100, n_jobs=-1,
                                                   param_distributions={'bootstrap': [True,
                                                                                      False],
                                                                        'max_depth': [None,
                                                                                      10,
                                                                                      20,
                                                                                      30],
                                                                        'max_features': ['sqrt',
                                                                                         'log2'],
                                                                        'min_samples_leaf': [1,
                                                                                             2,
                                                                                             4],
                                                                        'min_samples_split': [2,
                                                                                              5,
                                                                                              10],
                                                                        'n_estimators': [50,
                                                                                         100,
                                                                                         200,
                                                                                         300]},
                                                   random_state=42)),
                               ('lg',
                                GridSearchCV(cv...
                                                         'solver': ['liblinear']},
                                             scoring='accuracy'))],
                   final_estimator=RandomizedSearchCV(cv=3,
                                                      estimator=RandomForestClassifier(),
                                                      n_iter=100, n_jobs=-1,
                                                      param_distributions={'bootstrap': [True,
                                                                                         False],
                                                                           'max_depth': [None,
                                                                                         10,
                                                                                         20,
                                                                                         30],
                                                                           'max_features': ['sqrt',
                                                                                            'log2'],
                                                                           'min_samples_leaf': [1,
                                                                                                2,
                                                                                                4],
                                                                           'min_samples_split': [2,
                                                                                                 5,
                                                                                                 10],
                                                                           'n_estimators': [50,
                                        

In [35]:
# Đánh giá mô hình Stacking với SVC
evaluate_model(stacking_clf_finetuneRF, x_train, y_train, x_test, y_test)

StackingClassifier - Cross-validation scores: [0.748122   0.74296316 0.74513531 0.73662775 0.73346004]
Mean cross-validation score: 0.7412616526382478

StackingClassifier - Accuracy Score: 0.7502896032435563
StackingClassifier - F1 Score: 0.7496368758843558
StackingClassifier - Classification Report:
               precision    recall  f1-score   support

         0.0       0.76      0.70      0.73      6723
         1.0       0.74      0.80      0.77      7089

    accuracy                           0.75     13812
   macro avg       0.75      0.75      0.75     13812
weighted avg       0.75      0.75      0.75     13812

StackingClassifier - Confusion Matrix:
 [[4726 1997]
 [1452 5637]]
--------------------------------------------------


In [12]:
import joblib
#save model RF

joblib.dump(rf_ramdom, '../../results/output_files/B3_RFmodel_finetune.pkl')

['../../results/output_files/B3_RFmodel_finetune.pkl']

In [17]:
#save model Logictic
joblib.dump(lg_grid, '../../results/output_files/B3_LGmodel_finetune.pkl')

['../../results/output_files/B3_LGmodel_finetune.pkl']

In [22]:
#save model Stacking
joblib.dump(stacking_clf, '../../results/output_files/B3_Stackingmodel_withoutfinetune.pkl')

['../../results/output_files/B3_Stackingmodel_withoutfinetune.pkl']

In [26]:
#save model Stacking
joblib.dump(stacking_clf_finetune, '../../results/output_files/B3_Stackingmodel_with_finalLG.pkl')

['../../results/output_files/B3_Stackingmodel_with_finalLG.pkl']

In [30]:
#save model Stacking
import joblib
joblib.dump(stacking_clf_finetuneRF, '../../results/output_files/B3_Stackingmodel_With_finalRF.pkl')

['../../results/output_files/B3_Stackingmodel_With_finalRF.pkl']